
export const ALL_RESTAURANTS_FETCHING = 'restaurants.ALL_RESTAURANTS_FETCHING'
export const RESTAURANT_FETCHING = 'restaurants.RESTAURANT_FETCHING'
export const RESTAURANT_FETCHED = 'restaurants.RESTAURANT.FETCHED'
export const RESTAURANT_FETCHED_EMPTY = 'restaurants.RESTAURANT.FETCHED_EMPTY'
export const RESTAURANT_FETCH_ERROR = 'restaurants.RESTAURANT_FETCH_ERROR'
export const ALL_RESTAURANTS_FETCHED = 'restaurants.ALL_RESTAURANTS_FETCHED'
export const RESTAURANT_SELECTED = 'restaurants.RESTAURANT_SELECTED'
